### ISSUE TITLE
'HTTPMessage' object has no attribute 'getheader'

### ISSUE THREAD

**Issue by alatriste-lee** [DelightRun/PyBaiduYuyin#6]
# content_type = response.info().getheader('Content-Type')

Connected to pydev debugger (build 162.1967.10)
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/lxislx/PycharmProjects/PyBaiduYuyin百度语音/PyBaiduYuyin/__init__.py", line 483, in <module>
    t.say("你好，这里是百度语音识别模块测试")
  File "/Users/lxislx/PycharmProjects/PyBaiduYuyin百度语音/PyBaiduYuyin/**init**.py", line 191, in say
    content_type = response.info().getheader('Content-Type')
AttributeError: 'HTTPMessage' object has no attribute 'getheader'

**Comment by JuneUncle** [comment]
If you have solved this problem？ Thanks！

**Comment by prakasa1904** [comment]
solve it ?
